name: "my first action"

on:
  push:
    branches: ["main"]

jobs:
  display-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in my repo
        run: ls -lh
